version: "3.2"
services:
  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PG_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - OUTLINE_API_KEY=${OUTLINE_API_KEY}
      - TOP_K = ${TOP_K}
    restart: unless-stopped

  postgres:
    image: ankane/pgvector:latest
    volumes:
      - ./backend/database-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 30s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

  # frontend:
  #   image: optional_service_image
  #   profiles: ["optional"]
